### ISSUE TITLE
Removal of Tiberium Flechette Rifle

### ISSUE THREAD

**Issue by Profugo-Barbatus** [Profugo-Barbatus/TiberiumRim#15]
Bugged, pre-alpha weapon that was initially little more than purposeless messing around in XML. Time to kill it.

**Comment by RealTelefonmast** [comment]
Did so on my part, as well as a few def changes - going to make a pull for those after the fixed infection bug

**Comment by Profugo-Barbatus** [comment]
Negative, if you've completed an issue, make a pull for it. Don't pull the additional def changes until your done, unless they're directly related to the removal of the rifle (Removing the hediff it causes, and so forth)

**Comment by RealTelefonmast** [comment]
Uploaded a branch with the Rifle removed, went through all defs to make sure they are all done and nothing is missing, made tweaks that shouldn't and didn't (play-tested) cause any errors as it is only values.

Haven't made a pull for it as you mentioned *not* to make any other changes - which I already had done beforehand so I'm sorry about that - and just want to get your approval first of it being save to merge.

**Comment by Profugo-Barbatus** [comment]
Just open a pull request, approval or rejection of merges will be made through that.

**Comment by Profugo-Barbatus** [comment]
#17 Tiberium Rifle Now Removed
