### ISSUE TITLE
Every pawn who arrive on my map wear a Tiberium Protection Suit

### ISSUE THREAD

**Issue by Aldehyt** [Profugo-Barbatus/TiberiumRim#20]
like in Topic, only suit, mask is still random

I use v1.0.1

**Comment by Profugo-Barbatus** [comment]
It may have to do with the fact that the suits are *very* cheap compared to vanilla clothing. I'll investigate after the new year, and thank you for the report.

**Comment by Profugo-Barbatus** [comment]
#21 _should_ have resolved this issue.
