### ISSUE TITLE
Tiberium Eating Animal - Visceroid?

### ISSUE THREAD

**Issue by RealTelefonmast** [Profugo-Barbatus/TiberiumRim#23]
Some suggestion would be to implement an wild animal to reduce Tiberium spread, like the beavers with the trees, except that here it would be a Visceroid or other Tiberium lifeform that starts spawing on the map once there a certain amount of crystals has grown.-

**Comment by Profugo-Barbatus** [comment]
It'd require a significant number of the animals to impact the Tiberium population on the map, with their rate of reproduction. Such a solution would require aggressive rebalancing of Tiberium spread rates, but reducing spread rates to allow a population to easily control them would also remove the requirement for said population.
