### ISSUE TITLE
Let's make Tiberium be friends again

### ISSUE THREAD

**Issue by RealTelefonmast** [Profugo-Barbatus/TiberiumRim#30]
So I personally, and someone in the replies, would like Tiberium not to kill each other upon contact.
Especially since green Tiberium spreads quicker and further than any other type - leaving them no chance but becoming a green field as well.
This would change both the looks of multi-type fields and make gameplay easier of aquiring the different resources.

**Comment by Profugo-Barbatus** [comment]
Feature completed in Hugslib integration branch

**Comment by Profugo-Barbatus** [comment]
Integrated with optional settings into Hugslib Branch. Awaiting merge to confirm integration.

**Comment by Profugo-Barbatus** [comment]
Finished with #49
