### ISSUE TITLE
Explosive Tiberium

### ISSUE THREAD

**Issue by RealTelefonmast** [Profugo-Barbatus/TiberiumRim#35]
So lore wise blue Tiberium is supposed to be "highly combustible" - 
Red Tiberium as well.

It could be like a chain reaction with every crystal having a chance to explode - but also to remain.
So you don't get rid of a whole field - also told by lore.

Shall we add that in a future release?

**Comment by Profugo-Barbatus** [comment]
Implemented. Awaiting hugslib integration for closure.

**Comment by Profugo-Barbatus** [comment]
Finished with #49
