### ISSUE TITLE
Tiberium is temprature sensitive

### ISSUE THREAD

**Issue by Adraxas** [Profugo-Barbatus/TiberiumRim#36]
If the environment around tiberium gets too hot or cold, the tiberium growth will slow down/stop.

**Comment by RealTelefonmast** [comment]
Tiberium should not care about heat, it's not a plant in that sense.
Temperature however affects the crystals.
From other feedback we have found out that snow hinders Tiberium growth, and if it's gone it starts spreading again - which I personally think is a good solution to the issue.
