### ISSUE TITLE
Tiberium Inhibiter

### ISSUE THREAD

**Issue by RealTelefonmast** [Profugo-Barbatus/TiberiumRim#37]
For 1.2 we need some sort of building to stop Tiberium from growing, by killing it as long as it is powered.
I made a new branch for it and will upload the new building def and research for it soon.
A class is necessary as well though.

**Comment by Profugo-Barbatus** [comment]
Implemented. Awaiting hugslib integration for closure.

**Comment by Profugo-Barbatus** [comment]
Finished with #49
