### ISSUE TITLE
Vein Hole

### ISSUE THREAD

**Issue by RealTelefonmast** [Profugo-Barbatus/TiberiumRim#41]
A new type of tiberium field.
Harvestable veins instead of crystals, dont deal any infectious damage, but are still risky to walk through as they cause blunt damage randomly.
 
If possible:
Downed pawns and objects (items, corpses etc) will be slowy moved towards the center, getting bite, scratch and other feral damage in medium amounts.

It's immune to tiberium damage, but has low health.
The center hole is the weak point, "killing" it will destroy all connected or surrounding veins.

Veins refine into vein meat and a randomly small amount of either green or even more rarely blue tiberium.

Experimental:
Veins may emerge proto-visceroids, creatures made by tiberium evolution. 
Small, feral, harmless in small amounts. Bigger groups may cause havoc - the bigger a vein system the more proto-visceroids spawn.

**Comment by Profugo-Barbatus** [comment]
Stop assigning to out-of-scope goals for next release.

**Comment by RealTelefonmast** [comment]
Just suggesting. 
I still don't really quite know what parts might go out of scope or not.
I just assigned you because it seems to be more C# heavy than anything else.
Sorry for the inconvenience.
