### ISSUE TITLE
Tiberium Fauna and Blossom Trees

### ISSUE THREAD

**Issue by RealTelefonmast** [Profugo-Barbatus/TiberiumRim#43]
A good thing would be to have Tiberium Fauna spawn upon Tiberium spread, giving each tree or bush a chance to be replaced by Tiberium Fauna. 
Also there should be a very low chance of turning a tree into a Blossom Tree, rendering the existing event obsolete.

**Comment by Profugo-Barbatus** [comment]
Fauna implemented. Blossom tree's will wait for 1.3.

**Comment by Profugo-Barbatus** [comment]
Finished with #49 . Open separate issue for Blossom Tree behavior.
