### ISSUE TITLE
Tiberium Fiends

### ISSUE THREAD

**Issue by RealTelefonmast** [Profugo-Barbatus/TiberiumRim#45]
So I've started working on Tiberium Fiends, nothing too hard, just a tougher version of the infected animal.
So all that is necessary now is a tag in the defname to make them immune.
And of course a way to make Tiberium replace the corspe with a fiend or a visceroid.

**Comment by Profugo-Barbatus** [comment]
Please append "_TBI", for "TiBerium Immunity".

**Comment by RealTelefonmast** [comment]
Done, and pull requested it into hugslib-integration for testing purposes.
All fiends are ready and working on their own, just the "special" code is missing.

**Comment by Profugo-Barbatus** [comment]
Implemented, awaiting hugslib integration for closure.

**Comment by Profugo-Barbatus** [comment]
Finished with #49
