### ISSUE TITLE
Ion Storm

### ISSUE THREAD

**Issue by RealTelefonmast** [Profugo-Barbatus/TiberiumRim#67]
A suggestion I have is you should consider upgrading the Ion Storm to what it was famously for. It should essentially be literally, the combination of a Flash Storm, Eclipse, and Solar Flare all at once, lasting for approximately 2-8 hours typically. The Flash Storm would be on steroids, blasting crackling lightning strikes more frequently, with the sky becoming that characteristic orange-shroud we've seen in Tiberian Sun. Never more than an entire day lest max difficulty can do so.

**Comment by Nephlite** [comment]
This was a very fantastic experience.
