### ISSUE TITLE
Tiberium job type

### ISSUE THREAD

**Issue by RealTelefonmast** [Profugo-Barbatus/TiberiumRim#75]
Just like "Mine" or "Plant Cut", except that it is specified for Tiberium plants or rocks.
This is a player suggestion as they find it bothersome to have their unprotected plant cutters go out and die in the fields.
This possibly could be done by a detour prefix which would forbid any unprotected pawns to go and cut tiberium. Since creating a new job type wouldn't remove the harvestability of the Tiberium "Plant" and "Plant Cut" would still make pawns harvest it. 
Possibly the Tiberium attributes such as "cut" or "harvest" could be replaced by unique behaviours that don't rely on Plant.
This might need further discussion.

**Comment by Profugo-Barbatus** [comment]
Designator mods have hard compatibility issues with other designator mods because of how they work. I'm gonna have to hard no this until Tynan fixes the designator system to accept dynamic entries instead of hardcoding.
