### ISSUE TITLE
Tiberium Glaciers Create Build Roof Area

### ISSUE THREAD

**Issue by Stynche** [Profugo-Barbatus/TiberiumRim#79]
Hello!
It appears that when "Tiberium Glacier" grows to 100%, it also creates a yellow "Build Roof Area" in that tile.
I noticed that my one constructions guy kept traveling around and building roof around Glaciers. I think this is a bug? While I understand that you can just create a zone for a pawn where he is supposed to be, I do not think this was intended :D 
If its not a bug but just a way it is, then sorry for posting :)

Great mod btw, one of the best out there :)

**Comment by RealTelefonmast** [comment]
I guess you are playing the offline version. Sorry bout that, haven't uploaded the hotfix there yet.
