### ISSUE TITLE
Additional Tiberium Events

### ISSUE THREAD

**Issue by Profugo-Barbatus** [Profugo-Barbatus/TiberiumRim#8]
Please list all required custom C# events in this issue, and I'll assemble the needed IncidentWorkers for them.

**Comment by RealTelefonmast** [comment]
Randomly sized amounts of tiberium spawn at a certain location.
Like the asteroid, instead it's multiple objects scattered in a group.

--

Blue Tiberium can combine into a Tiberium Monolith.
If enough blue tiberium is at a 3x3 space, in the middle a of that bunch a tiberium monolith can be spawned for the cost of the cystals being killed. Very rare event.

--

Trees have a rare chance of becoming Blossom Trees when in contact to tiberium - Replaces "Unknown Gas!" event that spawns a tree at a random location. (Less important)

**Comment by Profugo-Barbatus** [comment]
Closed due to feature-lock for 1.0 release
